spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/operationcenter"
    username: root
    password: OperationCenter@2025
    driver-class-name: com.mysql.cj.jdbc.Driver
#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    enabled: true
logging:
  level:
    root: INFO
    org:
      springframework:
        jdbc:
          core: DEBUG